FROM golang:1.27-alpine AS builder
WORKDIR /app

COPY go.mod .
COPY go.sum .
COPY shared/ ./shared/
COPY cmd/passageiro/ ./cmd/passageiro/

RUN go build -o passageiro_bin ./cmd/passageiro/

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/passageiro_bin .
CMD ["./passageiro_bin"]